/**
 * Canonical list of FeedbackPin element IDs used across the app.
 * Add new IDs here as you wrap new elements with <FeedbackPin />.
 *
 * Keeping the union narrow gives us:
 *   - type-safety on <FeedbackPin elementId="…"> at compile time
 *   - a searchable registry when reviewing feedback
 *   - a way to de-duplicate identical pins across pages
 */
export const FEEDBACK_IDS = [
  // topbar / sidebar
  'topbar.toggleSidebar',
  'topbar.branchSelector',
  'topbar.userAvatar',
  'sidebar.locale',
  'nav.dashboard',
  'nav.pickup',
  'nav.finance',
  'nav.cod',
  'nav.branches',
  'nav.stock',
  'nav.prices',
  'nav.returns',
  'nav.provinces',

  // dashboard
  'dashboard.header',
  'dashboard.kpi.orders',
  'dashboard.kpi.collected',
  'dashboard.kpi.pending',
  'dashboard.kpi.locked',
  'dashboard.kpi.units',
  'dashboard.kpi.drivers',
  'dashboard.section.recentPickups',
  'dashboard.section.lockedWarehouse',
  'dashboard.lockedAlert',
  'dashboard.recentRow',
  'dashboard.lockedRow',

  // pickup module
  'pickup.header',
  'pickup.header.addNew',
  'pickup.filters.search',
  'pickup.filters.status',
  'pickup.filters.date',
  'pickup.filters.lastActivity',
  'pickup.filters.referenceCode',
  'pickup.filters.collection',
  'pickup.branchPills.all',
  'pickup.branchPills.hq',
  'pickup.branchPills.tag',
  'pickup.branchPills.oct',
  'pickup.branchPills.alx',
  'pickup.table.columnsToggle',
  'pickup.table.col.code',
  'pickup.table.col.client',
  'pickup.table.col.phone',
  'pickup.table.col.address',
  'pickup.table.col.weight',
  'pickup.table.col.status',
  'pickup.table.col.branch',
  'pickup.table.col.lastActivity',
  'pickup.table.col.referenceCode',
  'pickup.table.col.vehicle',
  'pickup.table.col.dispatch',
  'pickup.table.pagination',
  'pickup.row.dispatch',
  'pickup.row.view',
  'pickup.dispatchModal.confirm',
  'pickup.dispatchModal.vehicle.tagamoa_van',
  'pickup.dispatchModal.vehicle.october_van',
  'pickup.dispatchModal.vehicle.motorcycle',
  'pickup.create.form',
  'pickup.create.field.branch',
  'pickup.create.field.recipient',
  'pickup.create.field.phone',
  'pickup.create.field.address',
  'pickup.create.field.weight',
  'pickup.create.field.cod',
  'pickup.create.submit',
  'pickup.detail.timeline',
  'pickup.detail.recipient',
  'pickup.detail.package',
  'pickup.detail.money',

  // finance
  'finance.header',
  'finance.kpi.totalToCollect',
  'finance.kpi.collected',
  'finance.kpi.balance',
  'finance.filters.search',
  'finance.table.columnsToggle',
  'finance.table.col.driver',
  'finance.table.col.driverCode',
  'finance.table.col.branch',
  'finance.table.col.shiftDate',
  'finance.table.col.orders',
  'finance.table.col.delivered',
  'finance.table.col.returned',
  'finance.table.col.totalCod',
  'finance.table.col.cashCollected',
  'finance.table.col.variance',
  'finance.table.col.status',
  'finance.table.col.action',
  'finance.table.pagination',
  'finance.row.reconcile',
  'finance.row.approve',
  'finance.row.payOut',
  'finance.row.dispute',
  'finance.reconcileModal.actualCash',
  'finance.reconcileModal.notes',
  'finance.reconcileModal.submit',

  // cod
  'cod.header',
  'cod.kpi.due',
  'cod.kpi.paid',
  'cod.kpi.pending',
  'cod.filters.search',
  'cod.table.columnsToggle',
  'cod.table.col.client',
  'cod.table.col.code',
  'cod.table.col.phone',
  'cod.table.col.amount',
  'cod.table.col.orders',
  'cod.table.col.status',
  'cod.table.col.method',
  'cod.table.col.dueDate',
  'cod.table.col.action',
  'cod.table.pagination',
  'cod.row.pay',
  'cod.row.schedule',
  'cod.payModal.method',
  'cod.payModal.reference',
  'cod.payModal.amount',
  'cod.payModal.whatsapp',
  'cod.payModal.submit',

  // stock
  'stock.header',
  'stock.kpi.totalSkus',
  'stock.kpi.available',
  'stock.kpi.locked',
  'stock.kpi.totalUnits',
  'stock.branchPills.all',
  'stock.branchPills.hq',
  'stock.branchPills.tag',
  'stock.branchPills.oct',
  'stock.branchPills.alx',
  'stock.filters.search',
  'stock.filters.status',
  'stock.table.columnsToggle',
  'stock.table.col.sku',
  'stock.table.col.name',
  'stock.table.col.branch',
  'stock.table.col.quantity',
  'stock.table.col.status',
  'stock.table.col.lockReason',
  'stock.table.col.lastMovement',
  'stock.table.col.action',
  'stock.table.pagination',
  'stock.row.transfer',
  'stock.row.unlock',
  'stock.row.receive',
  'stock.unlockModal.reason',
  'stock.unlockModal.approver',
  'stock.unlockModal.submit',
  'stock.transferModal.destination',
  'stock.transferModal.quantity',
  'stock.transferModal.submit',

  // branches
  'branches.header',
  'branches.card',
  'branches.editForm',
  'branches.editForm.nameAr',
  'branches.editForm.nameEn',
  'branches.editForm.submit',

  // prices / returns / provinces
  'prices.header',
  'prices.comingSoon',
  'returns.header',
  'returns.comingSoon',
  'provinces.header',
  'provinces.table.columnsToggle',
  'provinces.table.col.nameAr',
  'provinces.table.col.nameEn',
  'provinces.table.col.code',
  'provinces.table.col.coverage',
  'provinces.row.toggle',
] as const;

export type FeedbackId = (typeof FEEDBACK_IDS)[number] | (string & {});
