// Generated by `mcp__Supabase__generate_typescript_types` for project
// "Twingo Logistics" (opqjsrmbivifjuhcjctt). Regenerate after schema changes.
// The repositories in lib/api/* map these Row shapes to the domain types in
// lib/types/*; this file exists for IntelliSense and typed Supabase queries.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      awb_batches: {
        Row: {
          branch_id: string;
          count: number;
          created_at: string;
          from_sequence: number;
          generated_by: string | null;
          id: string;
          to_sequence: number;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['awb_batches']['Row']> & {
          branch_id: string;
          count: number;
          from_sequence: number;
          id: string;
          to_sequence: number;
        };
        Update: Partial<Database['public']['Tables']['awb_batches']['Row']>;
        Relationships: [];
      };
      awb_codes: {
        Row: {
          batch_id: string | null;
          branch_id: string;
          code: string;
          created_at: string;
          generated_by: string | null;
          id: string;
          reserved_at: string | null;
          reserved_by: string | null;
          reserved_for_pickup_id: string | null;
          sequence: number;
          status: string;
          updated_at: string;
          used_at: string | null;
          used_for_pickup_id: string | null;
          voided_at: string | null;
          voided_by: string | null;
          voided_reason: string | null;
        };
        Insert: Partial<Database['public']['Tables']['awb_codes']['Row']> & {
          branch_id: string;
          code: string;
          id: string;
          sequence: number;
          status: string;
        };
        Update: Partial<Database['public']['Tables']['awb_codes']['Row']>;
        Relationships: [];
      };
      branches: {
        Row: {
          address: string | null;
          city: string | null;
          code: string;
          coverage_governorate_ids: string[];
          created_at: string;
          created_by: string | null;
          governorate_id: string | null;
          id: string;
          is_active: boolean;
          is_headquarters: boolean;
          location: Json | null;
          manager_id: string | null;
          name: Json;
          phone: string | null;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: Partial<Database['public']['Tables']['branches']['Row']> & {
          code: string;
          id: string;
          name: Json;
        };
        Update: Partial<Database['public']['Tables']['branches']['Row']>;
        Relationships: [];
      };
      cash_requests: {
        Row: {
          approved_at: string | null;
          approved_by: string | null;
          bank_account: string | null;
          client_id: string;
          cod_due_id: string | null;
          code: string;
          comment: string | null;
          created_at: string;
          id: string;
          paid_at: string | null;
          paid_by: string | null;
          payment_reference: string | null;
          rejection_reason: string | null;
          requested_amount: number;
          requested_method: string | null;
          status: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['cash_requests']['Row']> & {
          client_id: string;
          code: string;
          id: string;
          requested_amount: number;
          status: string;
        };
        Update: Partial<Database['public']['Tables']['cash_requests']['Row']>;
        Relationships: [];
      };
      cities: {
        Row: {
          code: string;
          display_order: number;
          governorate_id: string;
          id: string;
          is_active: boolean;
          name: Json;
        };
        Insert: Partial<Database['public']['Tables']['cities']['Row']> & {
          code: string;
          governorate_id: string;
          id: string;
          name: Json;
        };
        Update: Partial<Database['public']['Tables']['cities']['Row']>;
        Relationships: [];
      };
      client_shipping_rates: {
        Row: {
          base_price: number;
          client_id: string;
          cod_handling_fee_percent: number | null;
          created_at: string;
          fragile_surcharge: number | null;
          from_governorate_id: string;
          id: string;
          is_active: boolean;
          notes: string | null;
          to_governorate_id: string;
          updated_at: string;
          weight_tier: Json;
        };
        Insert: Partial<Database['public']['Tables']['client_shipping_rates']['Row']> & {
          base_price: number;
          client_id: string;
          from_governorate_id: string;
          id: string;
          to_governorate_id: string;
          weight_tier: Json;
        };
        Update: Partial<Database['public']['Tables']['client_shipping_rates']['Row']>;
        Relationships: [];
      };
      clients: {
        Row: {
          approval_requested_at: string | null;
          approval_status: string | null;
          approved_at: string | null;
          approved_by: string | null;
          business_name: Json | null;
          commercial_register: string | null;
          created_at: string;
          created_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
          email: string | null;
          id: string;
          is_active: boolean;
          name: Json;
          notes: string | null;
          payment_terms: Json;
          phone_primary: string;
          phone_secondary: string | null;
          pickup_address: Json;
          preferred_branch_id: string | null;
          rejection_reason: string | null;
          tax_number: string | null;
          total_cod_owed: number;
          total_orders: number;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: Partial<Database['public']['Tables']['clients']['Row']> & {
          id: string;
          name: Json;
          payment_terms: Json;
          phone_primary: string;
          pickup_address: Json;
        };
        Update: Partial<Database['public']['Tables']['clients']['Row']>;
        Relationships: [];
      };
      cod_dues: {
        Row: {
          accrual_period_end: string | null;
          accrual_period_start: string | null;
          client_id: string;
          code: string;
          created_at: string;
          deductions_notes: string | null;
          gross_cod_collected: number;
          id: string;
          net_amount_due: number;
          orders_count: number;
          other_deductions: number;
          paid_at: string | null;
          paid_by: string | null;
          payment_method: string | null;
          payment_reference: string | null;
          pickup_ids: string[];
          scheduled_payout_date: string | null;
          shipping_fees_deducted: number;
          status: string;
          updated_at: string;
          whatsapp_sent_at: string | null;
          whatsapp_template_used: string | null;
        };
        Insert: Partial<Database['public']['Tables']['cod_dues']['Row']> & {
          client_id: string;
          code: string;
          id: string;
          status: string;
        };
        Update: Partial<Database['public']['Tables']['cod_dues']['Row']>;
        Relationships: [];
      };
      districts: {
        Row: {
          city_id: string;
          code: string;
          id: string;
          is_active: boolean;
          name: Json;
        };
        Insert: Partial<Database['public']['Tables']['districts']['Row']> & {
          city_id: string;
          code: string;
          id: string;
          name: Json;
        };
        Update: Partial<Database['public']['Tables']['districts']['Row']>;
        Relationships: [];
      };
      driver_shifts: {
        Row: {
          actual_cash: number;
          approved_at: string | null;
          approved_by: string | null;
          branch_id: string;
          created_at: string;
          dispute_reason: string | null;
          driver_id: string;
          expected_cash: number;
          id: string;
          notes: string | null;
          orders_assigned: number;
          orders_cancelled: number;
          orders_delivered: number;
          orders_refused: number;
          orders_returned: number;
          paid_out_at: string | null;
          paid_out_by: string | null;
          reconciled_at: string | null;
          reconciled_by: string | null;
          shift_date: string;
          status: string;
          updated_at: string;
          variance: number;
          variance_reason: string | null;
        };
        Insert: Partial<Database['public']['Tables']['driver_shifts']['Row']> & {
          branch_id: string;
          driver_id: string;
          id: string;
          shift_date: string;
          status: string;
        };
        Update: Partial<Database['public']['Tables']['driver_shifts']['Row']>;
        Relationships: [];
      };
      governorates: {
        Row: {
          code: string;
          display_order: number;
          id: string;
          is_active: boolean;
          name: Json;
        };
        Insert: Partial<Database['public']['Tables']['governorates']['Row']> & {
          code: string;
          id: string;
          name: Json;
        };
        Update: Partial<Database['public']['Tables']['governorates']['Row']>;
        Relationships: [];
      };
      pickup_status_events: {
        Row: {
          id: number;
          note: string | null;
          pickup_id: string;
          reason_code: string | null;
          status: string;
          timestamp: string;
          user_id: string | null;
        };
        Insert: {
          id?: never;
          note?: string | null;
          pickup_id: string;
          reason_code?: string | null;
          status: string;
          timestamp?: string;
          user_id?: string | null;
        };
        Update: {
          note?: string | null;
          pickup_id?: string;
          reason_code?: string | null;
          status?: string;
          timestamp?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      pickups: {
        Row: {
          allow_open_package: boolean;
          branch_id: string;
          client_id: string;
          cod_amount: number;
          code: string;
          created_at: string;
          created_by: string | null;
          customer_notes: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
          delivered_at: string | null;
          delivery_address: Json;
          description: Json;
          dispatched_at: string | null;
          driver_id: string | null;
          driver_notes: string | null;
          expected_delivery_date: string | null;
          id: string;
          internal_notes: string | null;
          is_fragile: boolean;
          order_type: string | null;
          pieces_count: number;
          recipient: Json;
          reference_code: string | null;
          rejection_reason: string | null;
          review_status: string | null;
          reviewed_at: string | null;
          reviewed_by: string | null;
          shipping_fee: number;
          status: string;
          status_history: Json;
          submission_source: string | null;
          updated_at: string;
          updated_by: string | null;
          vehicle_type: string | null;
          weight_kg: number;
        };
        Insert: Partial<Database['public']['Tables']['pickups']['Row']> & {
          branch_id: string;
          client_id: string;
          delivery_address: Json;
          description: Json;
          recipient: Json;
          status: string;
        };
        Update: Partial<Database['public']['Tables']['pickups']['Row']>;
        Relationships: [];
      };
      price_list_entries: {
        Row: {
          base_price: number;
          cod_handling_fee_percent: number | null;
          fragile_surcharge: number | null;
          from_governorate_id: string;
          id: string;
          is_active: boolean;
          to_governorate_id: string;
          weight_tier: Json;
        };
        Insert: Partial<Database['public']['Tables']['price_list_entries']['Row']> & {
          base_price: number;
          from_governorate_id: string;
          id: string;
          to_governorate_id: string;
          weight_tier: Json;
        };
        Update: Partial<Database['public']['Tables']['price_list_entries']['Row']>;
        Relationships: [];
      };
      return_manifests: {
        Row: {
          acknowledged_at: string | null;
          acknowledged_by_signature: string | null;
          branch_id: string;
          client_id: string;
          code: string;
          created_at: string;
          delivered_at: string | null;
          expected_delivery_date: string | null;
          id: string;
          notes: string | null;
          pickup_ids: string[];
          status: string;
          total_pieces: number;
          total_value: number;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['return_manifests']['Row']> & {
          branch_id: string;
          client_id: string;
          code: string;
          id: string;
          status: string;
        };
        Update: Partial<Database['public']['Tables']['return_manifests']['Row']>;
        Relationships: [];
      };
      stock_items: {
        Row: {
          barcode: string | null;
          branch_id: string;
          category: string | null;
          client_id: string | null;
          created_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
          description: Json | null;
          id: string;
          last_movement_at: string;
          locked_at: string | null;
          locked_by: string | null;
          locked_reason: Json | null;
          name: Json;
          quantity: number;
          reserved_at: string | null;
          reserved_for_pickup_id: string | null;
          sku: string;
          status: string;
          thumbnail_url: string | null;
          unit: string;
          unlock_reason: Json | null;
          unlocked_at: string | null;
          unlocked_by: string | null;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['stock_items']['Row']> & {
          branch_id: string;
          id: string;
          name: Json;
          sku: string;
          status: string;
          unit: string;
        };
        Update: Partial<Database['public']['Tables']['stock_items']['Row']>;
        Relationships: [];
      };
      stock_movements: {
        Row: {
          created_at: string;
          from_branch_id: string | null;
          id: string;
          quantity: number;
          reason: Json | null;
          related_pickup_id: string | null;
          stock_item_id: string;
          timestamp: string;
          to_branch_id: string | null;
          type: string;
          updated_at: string;
          user_id: string | null;
        };
        Insert: Partial<Database['public']['Tables']['stock_movements']['Row']> & {
          id: string;
          quantity: number;
          stock_item_id: string;
          type: string;
        };
        Update: Partial<Database['public']['Tables']['stock_movements']['Row']>;
        Relationships: [];
      };
      users: {
        Row: {
          auth_id: string | null;
          branch_id: string | null;
          created_at: string;
          created_by: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
          driver_code: string | null;
          email: string | null;
          id: string;
          is_active: boolean;
          license_number: string | null;
          name: Json;
          national_id: string | null;
          phone: string;
          role: string;
          updated_at: string;
          updated_by: string | null;
          vehicle_type: string | null;
        };
        Insert: Partial<Database['public']['Tables']['users']['Row']> & {
          id: string;
          name: Json;
          phone: string;
          role: string;
        };
        Update: Partial<Database['public']['Tables']['users']['Row']>;
        Relationships: [];
      };
      zones: {
        Row: {
          branch_ids: string[];
          code: string;
          color: string | null;
          created_at: string;
          governorate_ids: string[];
          id: string;
          is_active: boolean;
          name: Json;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['zones']['Row']> & {
          code: string;
          id: string;
          name: Json;
        };
        Update: Partial<Database['public']['Tables']['zones']['Row']>;
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      current_user_branch: { Args: Record<string, never>; Returns: string };
      current_user_id: { Args: Record<string, never>; Returns: string };
      current_user_role: { Args: Record<string, never>; Returns: string };
      is_admin: { Args: Record<string, never>; Returns: boolean };
      is_bilingual: { Args: { v: Json }; Returns: boolean };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
